FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/platform-website /server
COPY assets/ /assets/
EXPOSE 3000
USER nonroot:nonroot
ENTRYPOINT ["/server"]
