FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/platform-website /app/server
COPY assets/ /app/assets/
COPY docs/external/ /app/docs/external/
EXPOSE 3000
USER nonroot:nonroot
ENTRYPOINT ["/app/server"]
