FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETPLATFORM

WORKDIR /app

COPY ${TARGETPLATFORM}/platform-website /app/server
COPY assets /app/assets
COPY docs/versions /app/docs/versions
COPY docs/what-is-rezuscloud.md /app/docs/
COPY docs/contributing /app/docs/contributing

EXPOSE 3000

USER nonroot:nonroot

ENTRYPOINT ["/app/server"]
