name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup build environment
        uses: ./.github/actions/setup-build

      - uses: sigstore/cosign-installer@v4

      - uses: anchore/sbom-action/download-syft@v0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/docker-multiarch
        with:
          push_image: true
          tag_list: |
            ${{ github.ref_name }}
            latest
          version: ${{ github.ref_name }}
          git_commit: ${{ github.sha }}
          build_time: ""
